/*
 * This page contains the text to be put on the Doxygen main page
 */

/**
 * @mainpage  C++ API documentation
 *
 * This is the C++ API documentation of the Fast Network Simulation Setup
 * (FNSS) toolchain.
 *
 * This API allows users to import topologies, traffic matrices or event
 * schedules generated by the FNSS core library into C++ objects, so that
 * they can be used in a C++ simulator.
 *
 * For further information, please refer to the README file or visit the
 * website <a href="http://fnss.github.com">http://fnss.github.com</a>
 */
